version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: citymall
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    image: arkadcml/country-lang-app
    depends_on:
      - db
    ports:
      - '8000:8000'