version: "3.7"
services:
  postgres:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: citymall
    ports:
      - '5432:5432'
  server:
    image: arkadcml/country-lang-app
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    networks:
      - webnet
    environment:
      DB_HOST: db
networks:
  webnet: